# Changes here will be overwritten by Copier
_commit: v0.2.2
_src_path: gh:KyleKing/my_go_template
author_email: dev.act.kyle@gmail.com
author_name: Kyle King
author_username: kyleking
copyright_date: '2026'
development_branch: main
module_path: github.com/kyleking/gh-start-search
project_description: 'GH CLI extension to search your stars '
project_name: gh-start-search
project_type: cli
repository_namespace: kyleking
repository_provider: https://github.com
use_goreleaser: true

